services:
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    command: npm run dev
    volumes:
      - ./client:/app/client  # Adjust path to frontend code
    stdin_open: true
    tty: true
    depends_on:
      - server

  server:
    build: ./server
    container_name: server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - PORT=${SERVER_PORT}
      - MONGO_URI=${MONGO_URI}  # Adjust as needed for your environment
    volumes:
      - ./server:/app/server  # Adjust path to backend code
    command: npm run watch
    stdin_open: true
    tty: true
